### ISSUE TITLE
Split InvalidReturnType into PossiblyInvalidReturnType?

### ISSUE THREAD

**Issue by TysonAndre** [TysonAndre/psalm#12]
See upstream

**Comment by muglug** [comment]
This was mentioned in https://github.com/vimeo/psalm/issues/285

I've added five new issues (currently not documented):

- `NullableInferredReturnType`
- `NullableReturnStatement`
- `FalsableInferredReturnType`
- `FalsableReturnStatement`
- `MixedReturnStatement`

Together with `LessSpecificReturnStatement` and `MoreSpecificReturnType`, I think these capture the bulk of potential problems with return types.

Some issues are still just `InvalidReturnType`/`InvalidReturnStatement`, such as

```php
class A {}
class B {}

function getAorB() : A {
  return rand(0, 1) ? new A : new B;
}
```
