### ISSUE TITLE
Try to avoid **invoking** autoloader to the largest possible extent

### ISSUE THREAD

**Issue by TysonAndre** [TysonAndre/psalm#8]
E.g. great for performance, but causes unpredictable crashes.

Continue using composer's autoloader, and support autoloader which returns a file, but doesn't actually `require_once`/`require` it

**Comment by muglug** [comment]
I'm being nosy, but I recently added https://github.com/vimeo/psalm/commit/becce4ae3600fff7a04cdc0d5770526bb25fcfd7 which eliminated virtually all autoloading for Vimeo's codebase.

**Comment by TysonAndre** [comment]
Do you mean that require_once won't be called on the vast majority of files in vendor/, but Psalm is still aware of their signatures (If the analyzed code uses them)?

**Comment by muglug** [comment]
Yes - Reflection is only ever used to get the file name for a given user-defined class (Psalm handles the rest in `ProjectChecker::scanFiles`, and that new composer hack circumvents that ReflectionClass instantiation.

**Comment by muglug** [comment]
I've added https://github.com/vimeo/psalm/commit/db7abc2b9062fce4cae4bcd6d9a7d559472c826e to provide more information when debugging issues.

**Comment by muglug** [comment]
I can also add a hack that scans the PSR-4 folders to determine paths to non-vendor files, when Psalm isn't analysing the entire codebase.
